[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "Photo_Renommer"
version = "1.0.1"
description = "Renommeur de Photo"
authors = [
  { name="Guillaume Delbarre" }
]

[tool.setuptools.packages.find]
where = ["."]